### PR TITLE
Update mustache package to fix PHP 8 error.

### PR DESCRIPTION
**Pull request by jeffreyvr**
The version of the mustache package that is included in the plugin causes an fatal error with PHP 8.

This pull request updates the package to the latest version. I have also added the packages to `composer.json` to allow for quicker updates in the future.

I haven't found any issues after applying these changes. Tested with PHP 8 and 7.4, but should also work on 5.6.

### CODE REVIEW

**Comment by bonakor** [comment]
This also seems to fix this issue: https://github.com/Yoast/wordpress-seo/issues/17453.

**Comment by bonakor** [comment]
But I'm getting this error: 
`contextual_help is <strong>deprecated</strong> since version 3.3.0! Use get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab() instead.`

**Comment by jeffreyvr** [comment]
@bonakor That appears to be coming from the scb-framework package which is used in this plugin.

https://github.com/scribu/wp-scb-framework/issues/55

**Comment by bonakor** [comment]
It's making it not that easy to update.

What would you recommend @jeffreyvr ?

**Comment by jeffreyvr** [comment]
@bonakor Think I'll use my forked version until the official plugin gets updated. Might also fork the wp-scb-framework package while I'm at it.

**Pull request merged**
